### PR TITLE
add: new disclosureFrame definition to allow array in arrays

### PR DESCRIPTION
**Pull request by ragnika**
DisclosureFrame is now
```
{
  _sd: [ <property key> | <array item index> ],
  [<property key> | <array item index>]: DisclosureFrame
}
```

### CODE REVIEW

**Review by linasi — APPROVED** [review]
@ragnika looks good. Although, I must admit that disclosure frame structure is very confusing to me.
Either we need better documentation or make it more clear somehow. We can discuss it tomorrow. 
If you have ideas on what other structures for the disclosure frame we can use - please let me know

Also, I see that you use quite a lot of checks `typeof variable === 'object'`.
Just to make sure you know that `typeof [] === 'object'` will return `true` as well?

**Comment by linasi** [comment]
@ragnika [this is](https://stackoverflow.com/questions/8511281/check-if-a-value-is-an-object-in-javascript) an interesting thead to read. Depends on what do we consider `object` in this context - different approach can be taken.

**Comment by ragnika** [comment]
> Also, I see that you use quite a lot of checks typeof variable === 'object'.
> Just to make sure you know that typeof [] === 'object' will return true as well?

@linasi yes, those are intentional, I'm checking for either object or array. I need to refactor the DisclosureFrame check since the new version can no longer be an array.

**Comment by ragnika** [comment]
> that disclosure frame structure is very confusing to me

@linasi Yea, it gets kind of confusing if you're going too many levels deep, but I think it's fairly manageable with simpler docs
Will definitely need to add a bit more examples or better examples in the readme to explain how it works.

for flat structures it's simply
`const DisclosureFrame = { _sd: ['key1', 'key2'] }`
which translates to the resulting sd-jwt
```
const packedClaims = {
  _sd: [
     <hash>, // hash for key1
     <hash>  // hash for key2
   ]
}
```

**Pull request merged**
